// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// extract_front_matter.cpp
list extract_front_matter_cpp(std::string text);
extern "C" SEXP _frontmatter_extract_front_matter_cpp(SEXP text) {
  BEGIN_CPP11
    return cpp11::as_sexp(extract_front_matter_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(text)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_frontmatter_extract_front_matter_cpp", (DL_FUNC) &_frontmatter_extract_front_matter_cpp, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_frontmatter(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
